#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions

# pre-process
m4 system/blockMeshDict.m4 > system/blockMeshDict
runApplication blockMesh
runApplication topoSet
runApplication setsToZones -noFlipMap
runApplication restore0Dir
# application
runApplication setFields
runApplication $(getApplication)
